### ISSUE TITLE
Migrate the build files to .NET CLI 2 and update the NuGet packages

### ISSUE THREAD

**Issue by hadibrais** [mellinoe/CrazyCore#1]
The .csproj files need to be migrated to use the .NET CLI 2.x tools. In addition, the NuGet packages need to be updated. I am not able to compile the code on Linux because of that.

**Comment by mellinoe** [comment]
Hey @hadibrais , check out the "new-new-dotnet-build" branch:

https://github.com/mellinoe/CrazyCore/tree/new-new-dotnet-build

There are still some things that could be cleaned up in there, but it should work with the MSBuild-based CLI just fine.

**Comment by hadibrais** [comment]
@mellinoe Now I'm able to to restore all packages and build the code. But which assembly contains the entry point? I tried CrazyCore.dll but it's not it.

**Comment by mellinoe** [comment]
To build the game project itself, you will need to open it up in the editor and then "publish" it.

* Open up Editor.exe. For example: "CrazyCore\code\ge\bin\Debug\Editor\netcoreapp1.1\win7-x64\publish\Editor.exe", after it's built
* File -> Open Project
![image](https://cloud.githubusercontent.com/assets/8918977/25068835/3e513c78-2224-11e7-95a6-4f0e7d6a4f90.png)
* Type in path to CrazyCore.manifest
* File -> Publish -> win7-x64
An explorer window pops up showing you the produced executable file which launches the game.

**Comment by hadibrais** [comment]
Note that I'm on Ubuntu 16.04. There are two executables called Editor located under:

/CrazyCore/code/ge/bin/OSX_Release/Editor/netcoreapp1.1/ubuntu.16.04-x64
/CrazyCore/code/ge/bin/OSX_Release/Editor/netcoreapp1.1/ubuntu.16.04-x64/publish

When I ran the program, it crashes with a DirectoryNotFoundException because it could not find /CrazyCore/code/ge/bin/OSX_Release/Editor/netcoreapp1.1/ubuntu.16.04-x64/PublishItems. The folder PublishItems is actually located under:

/CrazyCore/code/ge/bin/OSX_Release/Editor/netcoreapp1.1/ubuntu.16.04-x64/ubuntu.16.04-x64/publish

So obviously it will not find it. Anyway, I copied the folder to the directory where it should be and ran the editor again. It crashed with following stack trace:

-----
Unhandled Exception: System.InvalidOperationException: UniformBuffer 49 not uploaded correctly. Expected:64, Actual:0
   at Veldrid.Graphics.OpenGL.OpenGLBuffer.ValidateBufferSize(Int32 expectedSizeInBytes)
   at Veldrid.Graphics.OpenGL.OpenGLBuffer.EnsureBufferSize(Int32 dataSizeInBytes)
   at Veldrid.Graphics.OpenGL.OpenGLBuffer.SetData[T](T& data, Int32 dataSizeInBytes, Int32 destinationOffsetInBytes)
   at Veldrid.Graphics.OpenGL.OpenGLBuffer.SetData[T](T& data, Int32 dataSizeInBytes)
   at Veldrid.Graphics.DynamicDataProvider`1.SetData(ConstantBuffer buffer)
   at Veldrid.Graphics.OpenGL.OpenGLShaderConstantBindings.UniformBlockBinding.SetData(ConstantBufferDataProvider dataProvider)
   at Veldrid.Graphics.OpenGL.OpenGLShaderConstantBindings.ApplyPerObjectInputs(ConstantBufferDataProvider[] dataProviders)
   at Veldrid.Graphics.Material.ApplyPerObjectInputs(ConstantBufferDataProvider[] dataProviders)
   at Engine.Graphics.WireframeShapeRenderer.Render(RenderContext rc, String pipelineStage)
   at Veldrid.Graphics.Pipeline.StandardPipelineStage.ExecuteStage(VisibiltyManager visibilityManager, Vector3 viewPosition)
   at Veldrid.Graphics.Renderer.RenderFrame(VisibiltyManager visibilityManager, Vector3 viewPosition)
   at Engine.Graphics.GraphicsSystem.UpdateCore(Single deltaSeconds)
   at Engine.GameSystem.Update(Single deltaSeconds)
   at Engine.Game.RunMainLoopCore()
   at Engine.Game.RunMainLoop()
   at Engine.Editor.Program.Main(String[] args)
-----

Not sure what's going on.

**Comment by hadibrais** [comment]
I also tried running the editor from the publish directory using the corerun host. It crashed with the following stack trace:
___
Unhandled Exception: System.ArgumentOutOfRangeException: The concurrencyLevel argument must be positive.
Parameter name: concurrencyLevel
   at System.Collections.Concurrent.ConcurrentDictionary`2..ctor(Int32 concurrencyLevel, Int32 capacity, Boolean growLockArray, IEqualityComparer`1 comparer)
   at Engine.Graphics.MaterialCache..ctor(GraphicsSystem gs) in /code/CrazyCore/code/ge/src/Engine/Graphics/MaterialCache.cs:line 14
   at Engine.Graphics.GraphicsSystem..ctor(OpenTKWindow window, Single renderQuality, GraphicsBackEndPreference backEndPreference) in /code/CrazyCore/code/ge/src/Engine/Graphics/GraphicsSystem.cs:line 100
   at Engine.Editor.Program.Main(String[] args) in /CrazyCore/code/ge/src/Editor/Editor/Program.cs:line 30
___
This is a different exception and trace!

**Comment by mellinoe** [comment]
That is actually extremely unusual. It looks like the default constructor for `ConcurrentDictionary` is throwing an exception, because (presumably) `Environment.ProcessorCount` is returning 0... VERY strange. Could you try to print out out "Environment.ProcessorCount" before that exception is thrown?

Just to confirm: you are able to run the editor with the included host in the publish directory, right?

**Comment by hadibrais** [comment]
Yes I tried with the default runtime (which is located in the publish directory) by running the command. `./Editor`. See this [comment](https://github.com/mellinoe/CrazyCore/issues/1#issuecomment-294334127) for the result.

**Comment by mellinoe** [comment]
> Unhandled Exception: System.InvalidOperationException: UniformBuffer 49 not uploaded correctly. Expected:64, Actual:0

I've seen this before, and I think it's either a bug in Veldrid or a bug in the graphics drivers that Veldrid isn't handling well. It should only be happening in Debug builds, though (it is part of debug validation).

I'm going to merge everything into the master branch and get it cleanly building with the new tooling today. I'll let you know when that's done.

**Comment by hadibrais** [comment]
@mellinoe Thanks. It would be great if you can get it working as soon as possible. I don't remember whether I compiled the code in Debug or Release mode. I'll try both.

**Comment by mellinoe** [comment]
Okay, I just went through and did a major cleanup of all of the project files, updated all of the submodules (which fixed other bugs), and made sure everything worked from a clean state. It's also pushed to the master branch now, rather than the new-new-dotnet-build branch.

I'd suggest doing this:

* Clean everything in the repo (`git clean -xdf && git submodule foreach --recursive git clean -xdf`)
* Checkout the master branch and update to latest
* Update all of the submodules (`git submodule update --init --recursive`)
* Restore everything (you should be able to just restore CrazyCore.sln)
* Build code/ge/src/Editor/Editor.csproj and code/src/CrazyCore/CrazyCore.csproj

You should be able to run either of the executables now (not just the one in the "publish" directory), or run it using `dotnet Editor.dll`. I changed how the `PublishItems` directory was copied.

By the way, I'm still curious about what `Environment.ProcessorCount` is returning for you on your machine... it seems really weird that the default constructor for `ConcurrentDictionary` was throwing an exception for you...

**Comment by hadibrais** [comment]
When using the corerun host, Environment.ProcessorCount is indeed -1. Very strange indeed.

Also, as you indicted, the System.InvalidOperationException is only thrown when the code is built in Debug mode. It works in Release mode (of course, using the dotnet host). It's strange that ProcessorCount is -1 only when corerun is used!

So eventually I followed the steps in the editor and published the binaries. This resulted in a bunch of files under:

/CrazyCore/Published/ubuntu.16.04-x64

The only native executable that I see is Engine.Launcher. This crashes with the following stack:

Unhandled Exception: System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Engine.Program.Main(String[] args)

Am I supposed to provide command line args or something?

**Comment by hadibrais** [comment]
When using the corerun host, Environment.ProcessorCount is indeed -1. Very strange indeed.

Also, as you indicted, the System.InvalidOperationException is only thrown when the code is built in Debug mode. It works in Release mode (of course, using the dotnet host). It's strange that ProcessorCount is -1 only when corerun is used!

So eventually I followed the steps in the editor and published the binaries. This resulted in a bunch of files under:

/CrazyCore/Published/ubuntu.16.04-x64

The only native executable that I see is Engine.Launcher. This crashes with the following stack:

Unhandled Exception: System.ArgumentNullException: Path cannot be null.
Parameter name: path
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Engine.Program.Main(String[] args)

Am I supposed to provide command line args or something?

**Comment by mellinoe** [comment]
It looks like the "Publish" functionality is a bit broken now. I'll have to take a look in a bit. In your case it looks like "Engine.Launcher" didn't get renamed to CrazyCore.

**Comment by mellinoe** [comment]
I think I fixed that.

**Comment by hadibrais** [comment]
Nope. Same problem. Are you able to successfully build and run the game on Ubuntu, or is it just me who is facing the problem?

**Comment by mellinoe** [comment]
The launcher file should get renamed to "CrazyCore" on this line: https://github.com/mellinoe/ge/blob/6595ad0935db22b47da480e9828812625fb2ab1d/src/Editor/Editor/ProjectPublisher.cs#L56.

It's kind of weird that everything else is getting published to that directory except for that part. If you rename it to "CrazyCore", does it work?

**Comment by hadibrais** [comment]
If I rename Engine.Launcher to CrazyCore and run it, it emits the following output:
___
Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

Usage: dotnet [common-options] [[options] path-to-application]

Common Options:
  --help                           Display .NET Core Shared Framework Host help.
  --version                        Display .NET Core Shared Framework Host version.

Options:
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Path to Application:
  The path to a .NET Core managed application, dll or exe file to execute.

If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.
___
This is actually the same as the output of the coreconsole host. Then I copied the CrazyCore.dll from the Published/Assets/Managed directory to the Published directory and ran the binary again. It emitted the following error:

Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'CrazyCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Aborted (core dumped)

This indicates that CrazyCore.dll has no entry point. Note that in all cases, I didn't specify any command-line args.

**Comment by hadibrais** [comment]
This makes sense. When coreconsole is named Engine.Launcher, it will look for a file named Engine.Launcher.dll and run it. When it's named CrazyCore, it will look for a file named CrazyCore.dll and run it. I think that CrazyCore.dll is supposed to have an entry point.

**Comment by mellinoe** [comment]
I think I understand what you're trying to do. The published output is already standalone and contains everything necessary to run the game; it's not designed to be launched from an external host.

The folder contains (or SHOULD contain, I guess something is missing for you):
* `dotnet`, renamed to `CrazyCore`
* `Engine.Launcher`, renamed to `CrazyCore.dll`. This should contain the entrypoint. It is not the same file as the one contained in Assets/Managed/CrazyCore.dll (Yes, a bit confusing and messy).
* CrazyCore.manifest, a text file describing how the game is structured and what managed assemblies to load which comprise the game

The host (`dotnet` renamed to `CrazyCore`) looks for CrazyCore.dll and launches it. It looks for a file called "CrazyCore.manifest" and then deserializes that. Then, it loads all of the managed assemblies listed in it (Assets/Managed/CrazyCore.dll), and then opens up the initial scene listed in the manifest.

**Comment by mellinoe** [comment]
Another obvious thing just popped into my head: things are probably messed up on OSX now, unless you specify some extra parameters. For example, these conditions don't really handle OSX: 

https://github.com/mellinoe/ge/blob/master/src/Editor/Editor.csproj#L4
https://github.com/mellinoe/ge/blob/master/src/Engine.Launcher/Engine.Launcher.csproj#L4

You could try changing those lines to `osx.10.10-x64`, or just passing `/p:RuntimeIdentifier=osx.10.10-x64` to `dotnet msbuild`.

**Comment by mellinoe** [comment]
Unfortunately I don't actually have a Mac to test this on or I could probably give better advice 😄 . In the past, I've borrowed someone else's MacBook when it was time to test there.
