### ISSUE TITLE
Unable to resolve projects

### ISSUE THREAD

**Issue by PartySky** [mellinoe/CrazyCore#3]
I try to restore projeckt but get this issue `Unable to resolve project`:
![2017-08-07 15 21 58](https://user-images.githubusercontent.com/30129799/29028350-47c1dee8-7b84-11e7-8b93-8ef4f212874a.png)

**Comment by mellinoe** [comment]
Hey @PartySky , have you cloned all of the submodules? You may just want to re-clone like this:

`git clone https://github.com/mellinoe/crazycore --recursive`

**Comment by PartySky** [comment]
Thank you it helps.

Now I can't restore packeges:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'ImageSharp (>= 1.0.0-alpha7-00006)' for '.NETStandard,Version=v1.3'.				
Error		Unable to resolve 'ImageSharp (>= 1.0.0-alpha7-00006)' for '.NETCoreApp,Version=v1.1 (osx.10.10-x64)'.				
Error		Unable to resolve 'ImageSharp (>= 1.0.0-alpha7-00006)' for '.NETCoreApp,Version=v1.1 (ubuntu.16.04-x64)'.				
Error		Unable to resolve 'ImageSharp (>= 1.0.0-alpha7-00006)' for '.NETCoreApp,Version=v1.1 (ubuntu.14.04-x64)'.				
Error		Unable to resolve 'ImageSharp (>= 1.0.0-alpha7-00006)' for '.NETCoreApp,Version=v1.1 (win7-x64)'.				
Error		Unable to resolve 'ImageSharp (>= 1.0.0-alpha7-00006)' for '.NETCoreApp,Version=v1.1'.				
Warning		Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11-rc2-24027 
 Editor (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160908-1) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.Net.Sockets (>= 4.1.0-rc2-24027) -> runtime.unix.System.Net.Sockets (>= 4.3.0) -> System.Net.Primitives (>= 4.3.0) 
 Editor (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160908-1) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.Net.Primitives (>= 4.0.11-rc2-24027)				
Warning		Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11-rc2-24027 
 Engine.Launcher (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160908-1) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.Net.Sockets (>= 4.1.0-rc2-24027) -> runtime.unix.System.Net.Sockets (>= 4.3.0) -> System.Net.Primitives (>= 4.3.0) 
 Engine.Launcher (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160908-1) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.Net.Primitives (>= 4.0.11-rc2-24027)				
Warning		Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11-rc2-24027 
 Engine.Launcher (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160908-1) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.Net.Sockets (>= 4.1.0-rc2-24027) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Net.Primitives (>= 4.3.0) 
 Engine.Launcher (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160908-1) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.Net.Primitives (>= 4.0.11-rc2-24027)				
Warning		Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11-rc2-24027 
 Editor (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160908-1) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.Net.Sockets (>= 4.1.0-rc2-24027) -> runtime.win.System.Net.Sockets (>= 4.3.0) -> System.Net.Primitives (>= 4.3.0) 
 Editor (>= 1.0.0) -> System.CommandLine (>= 0.1.0-e160908-1) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.Net.Primitives (>= 4.0.11-rc2-24027)				
Error		Unexpected dependency 'ImageSharp' with no version number.	CrazyCore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Engine.Launcher	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Engine.Launcher	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Engine.Launcher	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Engine.Launcher	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Engine.Launcher	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Veldrid.Assets	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Editor	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Editor	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Editor	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Editor	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Editor	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'ImageSharp' with no version number.	Engine	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	

I tried to make dotnet restore in console, it says that I'm not uthorized. But when I open this page  `https://www.myget.org/F/rox/api/v3/flatcontainer/imagesharp/index.json`
as uthorized user in browser, it gets 404 notfound status.

Consol log is:

> dotnet restore code/CrazyCore.sln
  Restoring packages for C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\ext\imgui.net\src\ImGui.NET\ImGui.NET.csproj...
  Restoring packages for C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\ext\sharpfont\SharpFont\SharpFont.NETCore.csproj...
  Generating MSBuild file C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\bin\obj\ImGui.NET\ImGui.NET.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\ext\sharpfont\bin\obj\SharpFont.NETCore\SharpFont.NETCore.csproj.nuget.g.props.
  Writing lock file to disk. Path: C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\bin\obj\ImGui.NET\project.assets.json
  Writing lock file to disk. Path: C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\ext\sharpfont\bin\obj\SharpFont.NETCore\project.assets.json
  Restore completed in 448,26 ms for C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\ext\sharpfont\SharpFont\SharpFont.NETCore.csproj.
  Restoring packages for C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\ext\veldrid\src\Veldrid.Assets\Veldrid.Assets.csproj...
  Restore completed in 448,37 ms for C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\ext\imgui.net\src\ImGui.NET\ImGui.NET.csproj.
  Restoring packages for C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\ge\ext\veldrid\src\Veldrid\Veldrid.csproj...
  Retrying 'FindPackagesByIdAsync' for source 'https://www.myget.org/F/rox/api/v3/flatcontainer/imagesharp/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsync' for source 'https://www.myget.org/F/rox/api/v3/flatcontainer/imagesharp/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Failed to retrieve information about 'ImageSharp' from remote source 'https://www.myget.org/F/rox/api/v3/flatcontainer/imagesharp/index.json'.\r [C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\CrazyCore.sln]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\Administrator\Documents\crazycore-reclone\crazycore\code\CrazyCore.sln]

**Comment by mellinoe** [comment]
I finally got around to fixing this stuff. There was some severe bit rot that prevented things from building, but it should be fixed now. Note that I'm not actually using this project anymore, but a few people have mentioned that they'd like to play around with it.

**Comment by ghost** [comment]
Tools > NuGet Package Manager
Choose Package sources add:
name: corefxlab
https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json
